### ISSUE TITLE
Build failed with stack version: 2.1.3

### ISSUE THREAD

**Issue by ensrationis** [airalab/devcon5#1]
ens@razer:\~/git/devcon5$ stack upgrade
Current Stack version: 2.1.3, available download version: 2.1.3
Skipping binary upgrade, you are already running the most recent version
ens@razer:~/git/devcon5$ stack build
Could not parse '/home/ens/git/devcon5/stack.yaml':
Aeson exception:
Error in $.packages[1]: failed to parse field 'packages': expected Text, encountered Object
See http://docs.haskellstack.org/en/stable/yaml_configuration/

**Comment by akru** [comment]
Fixed in https://github.com/airalab/devcon5/commit/d00b2e187a5c682822904535b25682a1d051d58f
